export const CREATE_TASK_ACTION = 'CREATE_TASK_ACTION';
export const DELETE_TASK_ACTION = 'DELETE_TASK_ACTION';
export const SET_EDIT_MODE_ACTION = 'SET_EDIT_MODE_ACTION';
export const SAVE_EDITED_TASK_ACTION = 'SAVE_EDITED_TASK_ACTION';
export const DISCARD_CHANGES_ACTION = ' DISCARD_CHANGES_ACTION';
